"""Initial migration

Revision ID: 48e4a811ffa1
Revises: 
Create Date: 2026-07-04 00:58:02.255184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e4a811ffa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('condition_name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conditions_code'), ['code'], unique=True)

    op.create_table('pengguna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('usia', sa.Integer(), nullable=True),
    sa.Column('program_studi', sa.String(length=100), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('symptom_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptoms_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('study_program', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('examination_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('examination_date', sa.DateTime(), nullable=False),
    sa.Column('detected_condition', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('selected_symptoms', sa.JSON(), nullable=False),
    sa.Column('explanation_trace', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=60), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_rule_code'), ['rule_code'], unique=True)

    op.create_table('sesi_pemeriksaan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pengguna_id', sa.Integer(), nullable=False),
    sa.Column('gejala_dipilih', sa.JSON(), nullable=False),
    sa.Column('kondisi_terdeteksi', sa.String(length=50), nullable=False),
    sa.Column('skor', sa.Integer(), nullable=False),
    sa.Column('explanation_trace', sa.JSON(), nullable=False),
    sa.Column('rekomendasi', sa.JSON(), nullable=False),
    sa.Column('tanggal_pemeriksaan', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pengguna_id'], ['pengguna.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sesi_pemeriksaan')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_rule_code'))

    op.drop_table('rules')
    op.drop_table('recommendations')
    op.drop_table('examination_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptoms_code'))

    op.drop_table('symptoms')
    op.drop_table('pengguna')
    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conditions_code'))

    op.drop_table('conditions')
    # ### end Alembic commands ###
